"""
Django settings for backend project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import mongoengine
import datetime

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-^35+nxo(0wkc*%i%u45443tlgkr@3t7j5(09^e4e4x@9ob=y#7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'rest_framework',
    'rest_framework_mongoengine',
    'corsheaders',  # Add CORS support
    'teams',  # your team management app
    'LoginInicio',  # your login app
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'corsheaders.middleware.CorsMiddleware',  # Add CORS middleware
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

# CORS Settings
CORS_ALLOW_ALL_ORIGINS = True  # For development only, restrict in production

ROOT_URLCONF = 'backend.urls'


TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],  # Añadir esta línea
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

STATIC_URL = '/static/'

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# REST Framework settings
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'LoginInicio.auth.MongoJWTAuthentication',  # Usar nuestro autenticador personalizado
        'rest_framework.authentication.SessionAuthentication',
    ),
    'DEFAULT_PERMISSION_CLASSES': (
        'rest_framework.permissions.IsAuthenticated',
    ),
    'EXCEPTION_HANDLER': 'rest_framework.views.exception_handler'
}

# JWT settings
JWT_AUTH = {
    'JWT_EXPIRATION_DELTA': datetime.timedelta(days=7),
    'JWT_ALLOW_REFRESH': True,
    'JWT_REFRESH_EXPIRATION_DELTA': datetime.timedelta(days=30),
    'JWT_PAYLOAD_HANDLER': 'LoginInicio.utils.jwt_payload_handler',
    'JWT_SECRET_KEY': SECRET_KEY,  # Usar la misma clave secreta que Django
    'JWT_VERIFY': True,
    'JWT_AUTH_HEADER_PREFIX': 'JWT',
}

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# MongoDB Connection (after the DATABASES section)
MONGO_URI = (
    "mongodb+srv://marcmartin:sneakztest@futboldashboard.b8tot2f.mongodb.net/"
    "dashboardFutbol?retryWrites=true&w=majority"
)

# Connect to MongoDB on application startup
mongoengine.connect(host=MONGO_URI)

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'gamepaparruchas@gmail.com'
EMAIL_HOST_PASSWORD = 'bkwl feeo qdfd qkec'
DEFAULT_FROM_EMAIL = 'Team Manager <gamepaparruchas@gmail.com>'


try:
    from django.core.mail import send_mail
    print("Enviando correo de prueba...")
    send_mail(
        'Prueba de correo desde Django',
        'Este es un mensaje de prueba para verificar la configuración de correo.',
        'Team Manager <gamepaparruchas@gmail.com>',
        ['marc.martin@inslapineda.cat'],
        fail_silently=False,
    )
    print("Correo de prueba enviado correctamente")
except Exception as e:
    print(f"ERROR al enviar correo de prueba: {str(e)}")